### PR TITLE
feat: preview response body

### LINKED ISSUE #315: response  preview  render
I send a request  to servers and get  a page status is 500. This page contains a glorified error message 。
Can I use this to see the results returned, as in the browser?

### PR DESCRIPTION
**Pull request by baojd42**
Added two buttons:
* "Preview" to render the response body
* "Raw" to display the raw response
menu

Closes #315 

Example:
* request http://www.github.com
* click on 'Preview', then webpage is rendered
github
* click on 'Raw', then the raw response is displayed
raw

### CODE REVIEW

**Comment by baojd42** [comment]
@Huachao sorry about that. Lint errors fixed now.

**Comment by Huachao** [comment]
@baojd42 I have an idea that do we allow these two features only when the response is of HTML, which makes no ambiguity. What's your opinion?

**Comment by baojd42** [comment]
> @baojd42 I have an idea that do we allow these two features only when the response is of HTML, which makes no ambiguity. What's your opinion?

Yeah, I think that's probably better. There is no need to "preview" the JSON-formatted response body. I'm gonna do it later this week. @Huachao

**Comment by baojd42** [comment]
Sorry for being so late.

The feature is now only displayed when the response is HTML.

Could you please have a look and see whether it can be merged?

Thanks. @Huachao

**Review by Huachao — APPROVED** [review]

**Comment by Huachao** [comment]
LGTM

**Comment by Huachao** [comment]
@baojd42 Merged, thanks

**Comment by voccer** [comment]
@baojd42 how to enable this feature.
I send a request to google.com but can see the `preview` button
image

**Comment by Huachao** [comment]
@voccer this will be published in the next release

**Comment by voccer** [comment]
thank

**Comment by mk-git** [comment]
> @voccer this will be published in the next release
is there anything like a roadmap when the next release comes out?

**Comment by pierre-rbs-investr** [comment]
Hi there, can you please release this version ? Or maybe you should deprecate the extension as it is no longer maintained.

**Comment by noeldamps** [comment]
Hello everyone,
this feature would be great. I don't find the Option in the latest release version. Is there a plan when the next release will be published?

**Pull request merged**
