### PR TITLE
add dotenvFilename and requestVariableScope settings, fix #578

### LINKED ISSUE #578: Dynamic envs | set env var by HTTP response
In Postman, I can set a environment-variable by HTTP response ,JSON response by adding these codes to Tests.
```js
const body = JSON.parse(responseBody);
if (body.code) {
       console.log(pm.response)
       pm.environment.set("code", body.code)
}
```
Can I do like this in REST-CLIENT?

### PR DESCRIPTION
**Pull request by crossjs**
would be useful for specifying custom dotenv files like .env.local, .env.development, etc.

### CODE REVIEW

**Comment by FDiskas** [comment]
And why it's closed?

**Comment by crossjs** [comment]
> And why it's closed?

for `restclient` is too heavy for me and i am developing a new client includes this feature.

anyway, if the PR is welcomed by the extension author, i would like to make a new PR again.

**Comment by FDiskas** [comment]
Actually dotenv package if you do not specify a dotenf file it will respect .env and .env.local or I misunderstood.

**Comment by crossjs** [comment]
> Actually dotenv package if you do not specify a dotenf file it will respect .env and .env.local or I misunderstood.

Sometimes we need more dotenv files like .env.development, .env.development.local etc.

**Comment by FDiskas** [comment]
What I'm trying to say that dotenv already included in this project - so why not use all possibilities.

**Pull request closed without merging**
